id: ef9c24f44bb0422aa0c43dd2c851454b
initial_creation_type: ocr
source_metadata:
  volumes:
    6de8a86aa67f4b3db531fb9136459487:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
